### ISSUE TITLE
Add a function to tile_source to get a specific tile at any level or magnification

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/large_image#100]

**Comment by manthey** [comment]
Would you like this to return a dictionary of information like the tile iterator returns per tile, or would you like it to just return the tile?

We could treat this exactly like the tile iterator, excepting that a `tile = {x: <x>, y: <y>}` is specified as if within all of the other specifications of the iterator (that is, if you specify a region, `x=0, y=0` is the top-left portion of that region, not of the whole image).   If a tile `level` is specified, then the specific image level would be used, regardless of what would be selected by the `region` and `scale` specifications.

Thoughts?

**Comment by cdeepakroy** [comment]
I feel it should take the same parameters that tileIterator takes for specifying `region`, `scale` etc

I feel the purpose of this function to get one specific tile directly instead of iterating to find it.

I think the dictionary like the one that tileIterator returns at each iteration will be useful.

**Comment by manthey** [comment]
Added in PR #103.
