### ISSUE TITLE
Using a staticmethod with the lru cache fails in Python 2

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/large_image#12]
The addition of `@staticmethod` in [server/tilesource/tiff.py](https://github.com/DigitalSlideArchive/large_image/blob/5c43ffb40f8e5872f5b518824e644e01756b449b/server/tilesource/tiff.py#L38)) breaks the viewer in Python 2.7.

**Comment by zachmullen** [comment]
How does this break things? I didn't realize there was any change in behavior of `staticmethod` between 2 and 3.

**Comment by manthey** [comment]
I don't know if it works in Python 3, but in Python 2, I get an error: `TypeError: TypeError("'staticmethod' object is not callable",)`

**Comment by manthey** [comment]
Fixed in PR #13.
