### ISSUE TITLE
Add a RESTful API for fetching / pushing image annotations

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#16]

**Comment by manthey** [comment]
@brianhelba I've rebased the branch you started and have been adding to it.  It is still very much a WIP, but if you want to look at it, I pushed it to the `rebased-annotations` branch.

The annotations are each associated with a Girder item, so we should probably hook into item events and delete associated annotations when the item is deleted.  Should there also be a DELETE /annotation/item/{item id} endpoint (or DELETE /item/{id}/annotation)?  And similarly, do we want/need a GET endpoint that is item-centric rather than annotation centric?

**Comment by brianhelba** [comment]
In keeping with the rest of Girder, and to provide maximum flexibility, I'd put all the end points under the top-level `/annotation/...`. Therefore you could either `DELETE /annotation/{annotation_id}` to remove a single annotation, or `DELETE /item/{item_id}`, and the event hooks would delete all annotations associated with that item, as you suggested.

Do note, while this garbage collection is a sane initial behavior, we are probably going to not garbage collect annotations in the future, since we don't want people to lose their own valuable annotations just because a different owner of an item (image) deleted the item. We just need to figure out how to deal with the invalid references, access controls, etc., which I'd rather handle as an incremental improvement (and it's easier to transition from auto-deleting things -> saving them than the other way around).

Again, in keeping with the Girder style, I'd say that `GET /annotation?itemId={}` is the right way to fetch annotations for an item (if not an outright mandatory query string parameter).

One important thing where we need to be a little ahead of the curve from Girder is how we handle "list" vs "detail" endpoints. Assuming that `GET /annotation` was allowed (or some variant with a query string), the elements of the returned JSON list should contain only a subset of the full annotation's fields, namely only those fields needed to display a high-level listing. Even with 50-element pagination, the full annotation's fields (for instance, `attributes` field) should only be returned in the `GET /annotation/{annotation_id}` call. In the first pass, I'm fine if we inline shapes to the document returned by `GET /annotation/{annotation_id}`, but we will obviously need to transition to something more scalable, like `GET /annotation/{annotation_id}/shape`, in the near future.

**Comment by manthey** [comment]
I agree completely.

For `GET /annotation`, my thought was that we wouldn't return any shape elements initially.  I'll also filter out the `attributes` property. For this instant, `GET /annotation/{id}` will return the complete data, both elements and attributes.

**Comment by brianhelba** [comment]
Sold.

**Comment by cdeepakroy** [comment]
@manthey @brianhelba can we close this now?

**Comment by manthey** [comment]
Added in PR #50.
