### ISSUE TITLE
Support reading image tiles directly from SVS files

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#17]
OpenSlide's Python interface supports random access to SVS file tiles. The data will have to be re-JPEG-encoded, as OpenSlide only seems to return a decoded RGB image for each tile.

**Comment by brianhelba** [comment]
The library is here: https://github.com/openslide/openslide-python

Here's an example of the usage we'd like to see: https://github.com/openslide/openslide-python/blob/master/examples/deepzoom/deepzoom_multiserver.py

**Comment by manthey** [comment]
I've found some [sample svs files](http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/).  In these, the levels do not form a continuous set like we've seen in the TIF files.  For instance, many of the files have what they term level 0 (full resolution) in tiles of either 256 pixels square or 240 pixels square, then a level with is 1/4 resolution, then a level which is 1/16 resolution.  The [official UI](http://openslide.org/api/python/) doesn't have an explicit way to get to the tile size, but for all of these sample images, we can get the tile size via `(OpenSlide image).properties['openslide.level[0].tile-width']`.

I think we should try to read the tile size via the properties and fall back to using 256 if we can't read it.

We can either only serve the levels that exist, or we can construct on-the-fly the tiles at the other levels by down-sampling higher resolution data.

Thoughts?

**Comment by dgutman** [comment]
I have a working version of this code already that works well... I'll get
this online this weekend so you can check it out...

**Comment by manthey** [comment]
Great.

**Comment by brianhelba** [comment]
@manthey Grab an SVS image from one of the subdirectories within: https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/anonymous/tumor/lgg/bcr/nationwidechildrens.org/tissue_images/slide_images/ for now, and let me know if you have the same issue.

We'll get you a final official test image later.

**Comment by manthey** [comment]
@brianhelba Yes, the random file I grabbed from that link has the same structure.

**Comment by manthey** [comment]
@dgutman I'm not sure how you generalized loading different sources (checking if a file is a valid ptif, svs, etc.).  I've already got the code to do that, if it is of use.

**Comment by dgutman** [comment]
Thanks--- ill post you what I have and then we can maybe chat on modnay

**Comment by brianhelba** [comment]
I've just reviewed the code that @manthey has so far, and it all LGTM so far. The issue that he previously described is also present in the Deepzoom API, but is just abstracted away. @manthey 's code is already dealing with it in the the best way possible, IMO.

As far as I understand, @manthey just needs to polish a few rough edges in the code and add testing. We're targeting that this be ready by 3/9 (next Wednesday).

**Comment by brianhelba** [comment]
Fixed by #28 .
