### ISSUE TITLE
Test and upgrade to Numpy 1.10.4

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#23]
Numpy 1.10.4 is now released on Conda. If it works, we should upgrade (``requirements.txt`` and Travis build) to use it.

I have noticed some weird behavior with ``pylibtiff`` on a machine where Numpy 1.10.4 was installed, but I haven't been able to definitively blame it on Numpy 1.10.4 yet. If it turns out there is a problem, we need to affirmatively blacklist this version of Numpy and document this issue.

**Comment by brianhelba** [comment]
@manthey Can you take a look at this? It should be fast, and I'm trying to ensure that this and https://github.com/DigitalSlideArchive/HistomicsTK are using the same Numpy.

**Comment by manthey** [comment]
I've been using numpy 1.10.4 on my machine all along, as I had a single instance of Girder with several plugins I was working on and one of them required it.  What sort of weird behavior were you having?

**Comment by brianhelba** [comment]
I was getting segfaults somewhere inside the initial ``import libtiff``. It's totally possible that this is unrelated to Numpy, but I had started to get the error after upgrading Numpy.

If 1.10.4 works for you, just go ahead and formally change ``requirements.txt`` and Travis.

**Comment by manthey** [comment]
Done in PR #24.
