### ISSUE TITLE
Shortcut large_image creation on a non-filesystem assetstore does not work

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#25]
If an otherwise-valid pyramidal TIFF in a non-filesystem assetstore is marked as a large_image, a new conversion process is started, instead of failing directly.

The problem is that a failure to read due to non-pyramidal file content and a failure to read due to being in a non-filesystem assetstore both return the same exception type.

**Comment by brianhelba** [comment]
If it's confusing where this is occurring, I can add links to the specific code. I just don't have time to do so now.

**Comment by manthey** [comment]
I will fix this so that non-assetstores throw a different exception and thus don't try to get processed as a job.

**Comment by manthey** [comment]
Addressed in PR #27.
