### ISSUE TITLE
Add an endpoint to get an image thumbnail

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#33]
This should return the image at its native aspect ratio (without any extra padding).

The endpoint will probably be at ``/api/v1/item/tiles/thumbnail``. It will probably take the following query string parameters:
* ``width``, taking an integer, which will rescale the image to be the specified width.
* ``height``, taking an integer, which will rescale the image to be the specified height. Since the native aspect ratio of the image should be preserved, it is an error for both ``width`` and ``height`` to be specified at the same time.
* If neither ``width`` nor ``height`` is specified, a sensible default for one of these parameters should be used, so that all thumbnails are returned in the same predictable size.
* ``encoding``, changing the image encoding of the output. At a minimum, JPEG and PNG should be supported.

For now, internally, the "top-level" image of the pyramid can be used to generate the output, even if it means upsampling. We will later add a dedicated endpoint for getting high-quality image regions of arbitrary size and location.

**Comment by dgutman** [comment]
I have a very simple piece of code to do that ... I showed it to Mohammed
yesterday and he can post the snippet..

dg

**Comment by brianhelba** [comment]
Let's have @manthey implement this branch, but please post any helpful code snippits from @dgutman or @mohammedkhalilia .

**Comment by brianhelba** [comment]
Fixed by #34 .
