### ISSUE TITLE
Add an image region cutout endpoint

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#35]
This HTTP endpoint should allow users to fetch a high-quality arbitrary region of a large image, in a variety of formats.

A few requirements:
* The size and position of the region may be specified by the user. This could be implemented as either parameters for the top-left and bottom-right edges of the image, or as an offset value and size of the image. Either way, the coordinates should be specified in base (highest resolution) layer pixel coordinates, with the origin at the top-left.
* By default, the output images should be at the original size. If a user attempts to fetch a large portion of a massive image, the endpoint is allowed to fail.
 * Failure should be graceful, with a sane error message that the requested region is too large.
* Options for JPEG quality, etc. should be exposed.
* Cookie auth should be permitted.

**Comment by brianhelba** [comment]
Instead of using in base layer pixel coordinates, some other protocols use a fractional representation (values 0.0 to 1.0) to specify the desired region within the image. I'm open to this idea, but I think the loss of precision isn't worth the occasional convenience.

Any thoughts?

**Comment by brianhelba** [comment]
We will also want to add an option to rescale the image, but this isn't strictly necessary for the first pass.

**Comment by manthey** [comment]
We could support all of the coordinate options you mention fairly easily.  It is just a matter of deciding how we want to specify the coordinates.  For instance, `top` and `left` along with either `width` and `height` or `right` and `bottom`.  If we want to support fractional representation, then we could add a `units` option which would default to `pixels` and could optionally be `fraction`.

Output scale would be done much like the thumbnail option, but if we will need to disambiguate the source width and height from the output width and height.  Perhaps `outputWidth` and `outputHeight`?  Alternately, if we used `width` and `height` for the output and `sourceWidth` and `sourceHeight` (or something similar) for the input, then this functionally becomes the same as the thumbnail method for small widths and heights.

**Comment by manthey** [comment]
Added in PR #42.
