### ISSUE TITLE
Fix occasional failures in the example client test

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#47]
For some reason, the example client test occasionally fails. This is probably indicative of a more general problem, which should be investigated.

**Comment by jbeezley** [comment]
I would recommend adding external dependencies via regular script tags rather than as blanket covered scripts.  See what I did for [HistomicsTK](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/plugin_tests/client/visualization.js).

**Comment by manthey** [comment]
I started working on client tests (including fixing this), but they are on hold pending some higher priority tasks.

**Comment by manthey** [comment]
This appears to have been resolved by PR #55.  If not, we should open a new issue (as the test this issue refers to no longer exists).
