### ISSUE TITLE
Cache loadmodel used with tile fetches

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/large_image#67]

**Comment by manthey** [comment]
@zachmullen Currently, we call `@loadmodel(model='item', map={'itemId': 'item'}, level=AccessType.READ)` to load the item record and validate that the user has access to the item before serving a tile.  Do you have some ideas on the best way to cache that?

We could get the token string (as done in `getCurrentToken` and the item ID, and if it has been recent enough (1 minute, perhaps), return the item model value.    We could listen to token, user, and item save events and invalidate the cache on those.  This means that an expired token could continue to be served tiles for that cache duration, but that we would skip three database hits per request (one for token, one for user, and one for item).  I think if we invalidate cache on appropriate save events (or even on all of them), then that would be the only security ramification.

**Comment by zachmullen** [comment]
Is it 1 tile per item, or does a single item contain all of the tiles?

**Comment by manthey** [comment]
One item will serve hundreds or thousands of tiles.

**Comment by zachmullen** [comment]
In that case, your plan sounds like the right one. 

> This means that an expired token could continue to be served tiles for that cache duration

I think this is totally fine if we set the cache timeout to a few minutes; token expiration typically happens on the order of days, so going an extra couple minutes won't offend anyone. If the token is explicitly deleted, we can listen to that event to invalidate the cache immediately.

**Comment by manthey** [comment]
Thanks.  I'll work on it some time soon.

**Comment by manthey** [comment]
Added in PR #68.
