### ISSUE TITLE
Add documentation to install large_image for use as a python toolkit

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/large_image#79]
This issue involves adding a section to `README.rst` on how to install large_image for use as a python toolkit.

Prior to installing large_image using `python setup.py install` or `pip install -e large_image`, openslide and its dependencies need to be [installed](https://github.com/DigitalSlideArchive/base_docker_image/blob/master/Dockerfile#L5-L79). To begin with we can just have documentation for ubuntu 14.04 or ubuntu 16.04. But later we will need to add this for osx and windows.

**Comment by cdeepakroy** [comment]
CC: @manthey

**Comment by manthey** [comment]
This is done unless we want to tackle documenting installing OpenSlide.  I thought we had a write-up on that in one of the DSA repos, but I can't seem to locate that.

**Comment by cdeepakroy** [comment]
Instructions to build and install OpenSlide from source are [here](https://github.com/DigitalSlideArchive/digital_slide_archive/wiki/VIPS-and-OpenSlide-Installation)

**Comment by manthey** [comment]
Finished in PR #85.
