### ISSUE TITLE
Support small images

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/large_image#84]
Optionally support small images without having to convert them to a tiled image.  There should be an upper size limit beyond which this refuses to work so as not to use too much memory.

The UI should only show these if they have been marked in some way, which could happen automatically (off by default).

**Comment by dgutman** [comment]
So this works automatically with open sea dragon using legacy tile
sources... I can send the syntax.

**Comment by manthey** [comment]
Added in PR #99.
