### ISSUE TITLE
Add getRegionAtAnotherScale() - converts region from one scale to another

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/large_image#95]
Considering the region spec is the following dictionary:

* `left`: the left edge (inclusive) of the region to process.
* `top`: the top edge (inclusive) of the region to process.
* `right`: the right edge (exclusive) of the region to process.
* `bottom`: the bottom edge (exclusive) of the region to process.
* `width`: the width of the region to process.
* `height`: the height of the region to process.
* `units`: either 'base_pixels' (default), 'pixels', 'mm', or 'fraction'.

Add a function `getRegionAtAnotherScale(source_region, target_scale, source_scale=None)` that takes a region at `source_scale` and returns region at the `target_scale`. If units of `source_region` is `pixels`, then `source_scale` must not be None.

**Comment by cdeepakroy** [comment]
Also, later the usecase of converting a region spec from one type of units to another might come up.

**Comment by manthey** [comment]
In the event that the `units` of the source region is anything other than `pixels`, then this function ends up being just `getRegion(region=source_region, output=target_scale, **kwargs)`.  In the `units = pixels` case, more ends up being necessary.

I'll add a `convertRegionScale(source_region, target_scale, source_scale=None)` function that will output a region that can be passed to `getRegion` or `tileIterator`.  Do we need `tileIteratorAtAnotherScale` besides `getRegionAtAnotherScale`?

**Comment by cdeepakroy** [comment]
I don't have a use case for `tileIteratorAtAnotherScale` at the moment. But you may want to create an issue for it and we can address it when a use case arises. I can see some uses for it but not at the moment.

**Comment by manthey** [comment]
Added in PR #98.
